import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Montserrat } from "next/font/google";
import Link from "next/link";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "500"] });

export default function OtpPage() {
  return (
    <div className="flex items-center justify-center h-screen-[90vh] ">
      <Card className=" absolute top-[250px] w-full max-w-[537px] h-auto p-5 gap-2 border-[#BFBFBF] rounded-[10px] bg-white shadow-bottom-left sm:p-6 md:p-8">
        <CardHeader className="items-center justify-center mt-[20px] mb-[20px]">
          <CardTitle
            className={`${montserrat.className} font-medium text-[32px] leading-[100%]  tracking-[0%] text-center`}
          >
            Enter Auth Code
          </CardTitle>

          <CardDescription
            className={`${montserrat.className} font-normal text-[12px] leading-[100%] tracking-[0%] text-center mt-2`}
          >
            Enter a 6-digit code generated by Google Authenticator
          </CardDescription>
        </CardHeader>
        <CardContent className="flex justify-center items-center">
          <form className="flex flex-col gap-6 items-center">
            <div className="flex gap-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <input
                  key={i}
                  type="text"
                  maxLength={1}
                  className="w-[40px] h-[40px] sm:w-[50px] sm:h-[50px] border border-[#BFBFBF] rounded-md text-center text-lg outline-none focus:border-[#E0935A]"
                />
              ))}
            </div>

            <div className="flex items-center justify-center">
              <span
                className={`${montserrat.className} font-normal text-[16.27px] leading-[100%] text-center`}
              >
                If you don&apos;t receive the code?{" "}
                <span className="text-[#E0935A] font-bold">00:30</span>
              </span>
            </div>
            <Button
              className={`${montserrat.className} w-full sm:w-[457px] h-[50px] p-[15px] rounded-[2px] bg-[#E0935A] border-none text-amber-50 font-bold text-[16px] leading-[100%] tracking-[0.02em] text-center uppercase `}
            >
              Verify CODE
            </Button>
            <div className="flex justify-between items-center">
              <span
                className={`${montserrat.className} font-normal text-[16.27px] leading-[100%] `}
              >
                Back to?
              </span>
              <Link href="/login" className="text-[#E0935A]">
                Login
              </Link>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
